main:
  - name: Bio
    url: /
    weight: 10
  - name: Art√≠culos
    url: /#papers
    weight: 11
  - name: Charlas
    url: /#talks
    weight: 12
  - name: Noticias
    url: /#news
    weight: 13
  - name: Experiencia
    url: experience/
    weight: 20
  - name: Proyectos
    url: projects/
    weight: 30
  - name: Certificaciones
    url: certifications/
    weight: 40
